### ISSUE TITLE
book listings no longer work, website is linked to a porn blog.

### ISSUE THREAD

**Issue by WiggyWire** [spitbol/x64#10]
So a few issues, the Ed website you link to is a porn blog..., the newspaper article seems to be behind some sort of popup ad.

**Comment by WiggyWire** [comment]
Also I keep getting "No end statement found in source file", from your own demos? The program seems to be very broken - despite passing the 'sanity-test'. Whats happening - it seems that someone took the decision to switch to lower case despite all of the included documents using upper case letters?

**Comment by CheyenneWills** [comment]
Closing since the link is no longer present.

As for the upper/lower case issue, that is also currently "fixed", in that labels and variable names are now "folded" so that the case is pretty much ignored.

There are some problems with how folding is handled, specifically the output from datatype and the input to convert.
