### ISSUE TITLE
Discrepancy or a bug?

### ISSUE THREAD

**Issue by aksr** [spitbol/x64#22]
'123' RPOS(1) LEN(1) . OUTPUT
	END

`spitbol` *doesn't print anything* while both bunde's `csnobol4` and berstis' `snobol5` print `3`.

Discrepancy or a bug?

**Comment by CheyenneWills** [comment]
Not so much a bug, but there was a commit a while back that changed the default for &anchor from 0 to 1.

If you switch to unanchored mode (e.g. &anchor = 0), your test fixes the problem.

I will revert the default so that:

1) it is consistent with the other implementations
2) matches the last "pdf" documentation for SPITBOL.

**Comment by CheyenneWills** [comment]
I've pushed a development branch hopefully fixes this.    See the commit "Restore default value for &anchor to 0" should address the problem.

I'll be asking some folks to test this branch before promoting it to the main branch.

**Comment by aksr** [comment]
The issue is fixed. Thank you.
